### ISSUE TITLE
Enhancement request: data filed for overtake speed

### ISSUE THREAD

**Issue by cbrandlehner** [kartoone/mybiketraffic#1]
I would like to see an additional data field that displays overtake speed.

**Comment by kartoone** [comment]
Thanks for the suggestion. I’ve been working on that already, but the problem I’ve run into is that instead of a SimpleDataField, you have to use a regular DataField which requires the app to do more drawing and layout. I’ve never done that before, but I think I should have it figured out in the next few days … plus I’m also learning how to do settings so that the user can select how many (and which) fields they want to see.

**Comment by cagnulein** [comment]
@cbrandlehner  since @kartoone is away, do you have a simple FIT file that I can use for reference for #6 
Thanks!

**Comment by kartoone** [comment]
Didn't realize this issue was still open. You can add the overtake speed as one of the data fields displayed through the Garmin Connect IQ Store app which enables you to change settings easily on the MyBikeTraffic app or other Connect IQ apps you might have installed on your Garmin.
